In [2]:
import subprocess
import sys
import os
import platform
import ctypes
import requests

import ocr_main


#code to determine whether user is admin
def is_admin():
    try:
        return ctypes.windll.shell32.IsUserAnAdmin()
    except:
        return False

#code to run installation process of Tesseract as admin
def run_as_admin(command, folder=None):
    try:
        subprocess.run(['powershell', 'Start-Process', '-Verb', 'RunAs', '-FilePath', command], check=True)
    except subprocess.CalledProcessError as e:
        print(f"Error running as admin: {e}")

#installation of Tesseract
def install_tesseract():
    system_platform = platform.system().lower()

    if system_platform == 'windows':
        # Download the Tesseract installer
        tesseract_installer_url = 'https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-w64-setup-5.3.3.20231005.exe'
        installer_path = 'tesseract_installer.exe'

        try:
            # Download the installer
            response = requests.get(tesseract_installer_url)
            with open(installer_path, 'wb') as installer_file:
                installer_file.write(response.content)

            # Run the installer with elevated privileges
            run_as_admin(installer_path)

            # Remove the downloaded installer
            os.remove(installer_path)

        except Exception as e:
            print(f"Error downloading or running installer: {e}")
    else:
        print(f"Unsupported platform: {system_platform}")

# Run the script with elevated privileges
if is_admin():
    install_tesseract()
else:
    # Re-run only the Tesseract installation with elevated privileges
    tesseract_install_command = os.path.join(os.getcwd(), 'tesseract_installer.exe')
    run_as_admin(tesseract_install_command)

Error running as admin: Command '['powershell', 'Start-Process', '-Verb', 'RunAs', '-FilePath', 'C:\\Users\\noahc\\PycharmProjects\\CIBG-WNT-Parser\\OCR\\tesseract_installer.exe']' returned non-zero exit status 1.

In [3]:
import subprocess

# Install required packages
subprocess.run(['pip', 'install', 'pytesseract', 'Pillow'])

CompletedProcess(args=['pip', 'install', 'pytesseract', 'Pillow'], returncode=0)

In [4]:
from PIL import Image
import pytesseract
#set path to the tesseract executable, CHANGE THIS IF YOU SAVED IT SOMEWHERE ELSE
pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files\Tesseract-OCR\tesseract.exe'

In [11]:
# Open an image file
image_file_name = 'An_example_for_a_nailed_note.jpg'
image_path = '../OCR/testfiles/'

img = Image.open(image_path+image_file_name)

# Perform OCR on the image
text = pytesseract.image_to_string(img)

# Print the extracted text
print(text)

.-shehasnootherneurologicsymptomsnonumbnessortinglingshedeniesanyvisualcha
ngespastmedicalhistorygallbladderremovalpastsurgicalhistorydiabetesrheumatoida
rthritishypertensiongerdandhypothyroidismmedicationsadvairalbuterolallopurinol
aspirinclobetasolfolicacidfosamaxlevoxyllisinoprilmetforminomeprazoleplaquenilp
rednisonetestosteroneverapamilallergiesnoknowndrugallergiessocialhistorythepati
entismarriedwithchildshedoesnotsmokeshedoesnotdrinkshedoesnotuserecreation
aldrugssheweighspoundsandisinchestallfamilyhistorynegativeforbrainaneurysmoro
theraneurysmitwasalsonegativeforheartdiseasehighcholesterolandhypertensionand
negativefordiabetesreviewofsystemsthepatientispositiveforhypertensionswellingint
hehandsorfeetlegpainwhilewalkingasthmapneumoniashortnessofbreathgastritisule
ersdiabetesthyroiddiseaseurinarytractinfectionsandthosesymptomsrelatedtothepre
sentillnessthedetailsofthereviewofsystemswerereviewedwiththepatientandareinclu
dedintheneurosurgicalhealthhistoryquestionnairepainthepatienthasepisodicjointpa
inthatistreatedwithtylenolthepatientdoesnothaveanynutritionalconcernsshedoesno
thaveanysafetyconcernsphysicalexamination...

In [5]:
image_file_name = 'image 31.png'
img = Image.open(image_path+image_file_name)

# Perform OCR on the image
text = pytesseract.image_to_string(img)

# Print the extracted text
print(text)

sadable
wnac counttle mind-map

mnenss WOPGS. Support well Subject 2" heeled csqpoitina way

manage, Mother man rs Ty coniroy reading introduction

best Classic people Q ma rie Ci ng 1 lementation ;: seb
P

ets UGE atten meaning ore
show wing computer post +s | Cieshnicd used

cs evplalhSuesoeonacaN ei ait “ abe :

asSociqtions

intelligence ‘soon

standardized nicl ah
a ‘examples Approach |q

a4
. VQ

literacy rather s sem
stressing oi e dec 9
think somethi"@ clustering g Peary Sh

imprecise areas sustained now Part seetns pr actl sald
r 2) S ults difficulties ans DN ne S eqr lc slngon
G Si tle behavior feel arti Ic le S printed rf
engine O0JIe — contra ae booksiN ormation

ws Howe ier ,
ranking completel circuits, Powerset
ven my ata pace published author format

Enthasiast oppreciate one, incidentally
ensive

In [7]:
image_file_name = 'text-features-examples-and-definition-1024x724.jpg'
img = Image.open(image_path+image_file_name)

# Perform OCR on the image
text = pytesseract.image_to_string(img)

# Print the extracted text
print(text)

TEXT FEATURES

Text features refer to the organizational and structural elements of a text that generally help
with navigating and meaning-making.

OVERVIEW EXAMPLES

¢ Graphs/Charts: Visual
representations of data. They help
to illustrate and explain datasets
and relationships between data in a
fast and consumable way.

A text feature is an element of a text
that helps readers to make meaning of
the text. They could be used to
display information in easy-to-digest
ways, help compel the storyline
forward, help readers navigate a non-
linear text, and structure data in an
organized fashion. Without text
features, we would simply have big
blocks of text that would be tedious
to read and comprehend.

Table of Contents: A list of titles
or chapters and the page numbers
where they start, usually located at
the beginning of a book. They
allow readers to navigate the book
easily.

HELPFULPROFESSOR.COM

In [8]:
image_file_name = 'galton_orig.png'
img = Image.open(image_path+image_file_name)

# Perform OCR on the image
text = pytesseract.image_to_string(img)

# Print the extracted text
print(text)

116 Inquiries into Human Faculty

where previously there bad been vacunt
well-known rectory, fish-ponds, walls, etc., SP Sceed ah
show, came into view most vividly and cleanly deine
Thi omnes how suggested ‘another view, impressed on his
nood, of a spring morning, brilliant sun, and
bed of red tulips: the tulips gradually vanishe “ot one,
d d
which appeared now to be weolated and to sand in the uoal
ae of sight Ea as a single tulip, but became double.
en fell off rapidly in 2 continuous series until
there was nothing left but the pistil een
invariably the case with his objects) Games aeay
gzaggeraied, The stigmas then change into tvee ranch.
ing vows hors 4) } then into a knob (5), while the stalk
. A slight bend io
sarees a acansbie (sau pened inte « sod of pn
Bassng trough «metal pte (7), thib ain nt + lock &
ind afterwards into a nondescript shape (9), distantly sugges-
ve of the orignal crossbow. | Here-Mi, Henslow cade:
ive ad to farce his wil spon the visions, and to reproduce
a I attempt was an utte i
‘The figure changed into leather chap with Tope (ae) but
ils sl endeavoured to change it into bow tbe sty
broke, the two ends were separated, but it bappened that an
imaginary string connected them (rr). This was the first
concession, of his automatic chain of thooghts wo bis wil
3y a continued effort the bow came (1a), and then n
‘iGiculty was felt in converting it into the cross-bow, a
thus returning to the starting-point. an
Fig. 71. Mr. Henslow writes -—

“Though [ can usually summon uf 5

7 a any obj it

ag. calysanevhat itkeet fom thered tog, bat rapely

s changes are in many cases cl

Sea anche in the anicle of someting lee, but not always

46, a8 in some cases hereafter described. “I is not at all ‘Reece

sary io think of any parnlerobjert at, fst ss something is
r : ly within a minute

big Mang, nce appeared, the tomatiem of the brain wil

luce the series of changes. The images are someti

Veby Homerous, and very rapid ia successions very frequently

of great beauty and highly bilan Cat glans Garntee da te
jan I am conscious of ever having seen), highly chased gold

Visionaries 117

and silver filigree oraaments; gold and ever Aower-stands, etc.
aad sivey coloured. patterns of carpets in brilliant tints aze not
uncommon.

‘Another peculiarity resides in the extreme, restlessness of
any Anal objec. Ie is oten very dificult to keep them $y
Ty villas from changing in character. “They will rapidly oscile
waren tse rotate to a most perplexing degree, and when the
Tate or else Teange at the same time a critical examination 19
characters Jcaaible, When the process is in full activity, I feel
almost Impostinere spectator af a diorama of a very eccentric
as it Ui iwar in Bo way concerned with the getting ap of the
perfarmance.

Ty ben a succession of images has been passing, T sometimes
dene eittreduce an object cay a watch. | Very often it is
next to impossible to succeed, ‘TI is an evident struggle.
gat to ieipotmy ang simple, will not come ; hut some bybrid
Jaucture appears—something round, perhaps—but it Japses into
a warming-pan or other unexpected object,

wethis practice baa brought to my mind very clearly the di
tinction between at Teast one form of automatism of the brain
tingtion bee put the atrengih of the former is enormous, Tor
the visual objects, when in full career of the change, are impera-
dive in their refusal to be interfered with.

ug in hel ow describe the cases illustrated. Fig. 71. 7
thought of a gun, The stock came into view, the metal Pits or
though of etinct towards theleft (2). The wood was elabor
ately carved. [ cannot recall the patter: "Aa L scrutinised it,
Mey aye ccillated up and down, and crumpled 4p. The
metallic plate sank inwards: and the stock ‘contracted so that
metalic Dat tee a tuping-fork (2)- 1 gave up the stock and

proceeded cautiously to examine the lack. I got it well iato
procesded cotpore of the gus, Tt wormed ovt to be an olf
view, but Biiclock. Jt immediately began to, ned backwards
Sashloned Hs ia a mamner suggestive of the beak of a bind
aad foe equestly i fortnwath became converted into the Bees,
ing. Comedina fong, curved beak, the knob on she lock (3)
ofa Pine he head of the bird, { then looked to the itt
ecome fo find the barrel, but the snout of, saw-fsh $e)
expecting Minctly, broken off appeared instead. 1 had not
Oe UD deter of & flinblock of of a saw-fish: both came
‘spontaneously.

Sea 'T bave several times thought of @ rosebud: 26
Goce’ ig said to have been able to see one at will, and to
Gost, it expand. ‘The following are some of the results =~
akserys dt appeared unexpectedly a moss resebud) 1, 9m}
‘The bud APearance was the ioordinately elongated sepals (1),
qonorinel ce x wo expand. It enlarged but only partially

In [9]:
image_file_name = 'Balans-activa-Jaarrekening-bedrijf.png'
img = Image.open(image_path+image_file_name)

# Perform OCR on the image
text = pytesseract.image_to_string(img)

# Print the extracted text
print(text)

Balans - Activa

31-12-2018 31-12-2017

EUR EUR

VASTE ACTIVA 3.300.233.000 2.611.236.000
B. Immateriéle vaste activa x 216.000 146.000
C. Vastgoedbeleggingen xl 1.132.650.000 1.008.286.000
- Vastgoed beschikbaar voor verhuur 1.103.491.000 982.853.000
~ Projectontwikkelingen 11.550.000 6.121.000
- Andere: grondreserve 17.609.000 19.311.000
D. Andere materiéle vaste activa Xi 66.018.000 66.566.000
- Materiéle vaste activa voor eigen gebruik 2.293.000 1.876.000
- Andere: zonnepanelen 63.725.000  64.690.000
E.  Financiéle vaste activa Xill, XIV 2.100.345.000 1.535.416.000
- Activa aangehouden tot einde looptijd 3.252.000 5.764.000
Afdekkingsinstrumenten 3.252.000 5.764.000
~ Leningen en vorderingen 963.171.000 770.976.000
Andere 963.171.000 770.976.000
- Andere 1.133.922.000 _758.676.000

Deelnemingen in verbonden ondernemingen

en ondernemingen met een deelnemings-

verhouding. 1,133.922.000 _758.676.000
H. Handelsvorderingen en andere vaste activa 1.004.000 822.000
\VLOTTENDE ACTIVA 30.026.000 34.251.000
A. Activa bestemd voor verkoop xv 739,000 7.525.000
- Vastgoedbeleggingen 739.000 7.525.000
. Handelsvorderingen XVI 2.685.000 3.972.000
E. Belastingvorderingen en andere viottende activa Xvi 24.450.000 20.921.000
- Belastingvorderingen 60.000 1.285.000
- Andere vlottende activa 24.390,000 19,636,000
F. Kas en kasequivalenten 662.000 1.138.000
G. Overlopende rekeningen Xvill 1.489.000 694.000
- Gelopen, niet vervallen vastgoedopbrengsten 0 6.000
- Voorafbetaalde vastgoedkosten 286.000 132.000
- Voorafbetaalde intresten en andere financiéle kosten 77.000 70.000
- Andere 1.126.000 486.000

TOTAAL ACTIVA 3.330.259.000 2.645.486.000

In [10]:
image_file_name = 'kvk_jaarrekening_cijfers_jortt.jpg'
img = Image.open(image_path+image_file_name)

# Perform OCR on the image
text = pytesseract.image_to_string(img)

# Print the extracted text
print(text)

Cijfers

Balans

Balans voor of na resultaatbestemming

Balans

Activa

Vaste activa

Kosten van oprichting en van uitgifte van aandelen
Overige vaste activa

Vaste activa

Viottende activa

(Opgevraagde stortingen van geplaatst kapitaal
Overige viottende activa

Viottende activa

Activa

Passiva

Eigen vermogen

Voorzieningen

Schulden

Passiva

Ree Opsiaan en volgende

Voor

31-12-2017

31-12-2016

49001

40001

1000

1000

41001

39767

1234

41001

60001

60001

60001

60001

60001

In [11]:
img = Image.open('C:/Users/noahc/PycharmProjects/CIBG-WNT-Parser/experiments/pdf_to_table/2.png')

# Perform OCR on the image
text = pytesseract.image_to_string(img)

# Print the extracted text
print(text)

Effect of Wnt
signal on target

conn ee ee OID IED TEE EF OE EO

Effect of changes in
target gene expression Target gene

Target gene gene expression on Wnt pathway interacts with Reference

Fz Down Inactivate Wht (Muller et al. 1999)
Dfz2 Down Inactivate Wat (Cadigan et al. 1998)
Dfz3 Up Activate Wat (Sato et al. 1999)

Fz7 Up Wht (Willert et al. 2002)
Arrow/LRP Down Tnactivate Wht (Wehrli et al. 2000)
Daily (HSPG) Down Wht (aeg et al. 2001)
Wingful/notum Up Inactivate HSPG? (Giraldez et al. 2002)
naked Up Tnactivate Dsh (Rousset et al. 2001)
Axin2 Up Inactivate f-catenin (Tho et al. 2002)
B-TCRP Up Inactivate f-catenin (Spiegelman et al. 2000)
TCFI (dn) Up Inactivate TCF (Roose et al. 1999)
LEFI Down Activate f-catenin (CHovanes et al. 2001)
Nemo Up Inactivate (Drosophila) f-catenin/ (Zeng & Verheyen 2004,

Activate (Zebrafish) LEF/TCF

Thorpe & Moon 2004)

In [12]:
image_file_name = '2.png'
img = Image.open(image_path+image_file_name)

# Perform OCR on the image
text = pytesseract.image_to_string(img)

# Print the extracted text
print(text)

Target gene

Fz

Dfz2

Dfz3

Fr7
Arrow/LRP
Dally (HSPG)
Wingfull/notum
naked

Axin2
£-TCRP
TCFI (dn)
LEF]

Nemo

Effect of Wnt
signal on target
gene expression

Down
Down
Up
Up
Down
Down
Up
Up
Up
Up
Up
Down
Up

conn ee ee OID IED TEE EF OE EO

Effect of changes in
target gene expression Target gene

on Wnt pathway interacts with Reference
Tnactivate Wht (Muller et al. 1999)
Tnactivate Wht (Cadigan et al. 1998)
Activate Wht (Sato et al. 1999)
Wht (Willert et al. 2002)
Tnactivate Wht (Wehrli et al. 2000)
Wht (Baeg et al. 2001)
Inactivate HSPG? (Giraldez et al. 2002)
Tnactivate Dsh (Rousset et al. 2001)
Tnactivate f-catenin (Tho et al. 2002)
Inactivate f-catenin (Spiegelman et al. 2000)
Inactivate TCF (Roose et al. 1999)
Activate f-catenin (CHovanes et al. 2001)

Inactivate (Drosophila) f-catenin/
Activate (Zebrafish) LEF/TCF

(Zeng & Verheyen 2004,
Thorpe & Moon 2004)

In [13]:
import pandas as pd

# Split the text into lines
lines = text.split('\n')

# Create a DataFrame with each line as a new row
df = pd.DataFrame({'Text': lines})

# Display the DataFrame
df

                            Text
0                    Target gene
1
2                             Fz
3
4                           Dfz2
..                           ...
59  Activate (Zebrafish) LEF/TCF
60
61        (Zeng & Verheyen 2004,
62           Thorpe & Moon 2004)
63

[64 rows x 1 columns]

In [24]:
image_file_name = '2_clean.png'
img = Image.open(image_path+image_file_name)

#treats image as a single uniform block of text, ignoring any perceived line breaks
custom_config = r'--psm 3'

# Perform OCR with custom configurations
text = pytesseract.image_to_string(img, config=custom_config)

# Print the extracted text
print(text)

# Split the text into lines
lines = text.split('\n')

# Create a DataFrame with each line as a new row
df = pd.DataFrame({'Text': lines})

# Display the DataFrame
df

Target gene

Fz

Dfz2

Dfz3

Fr7
Arrow/LRP
Dally (HSPG)
Wingfull/notum
naked

Axin2
£-TCRP
TCFI (dn)
LEF]

Nemo

Effect of Wnt
signal on target
gene expression

Down
Down
Up
Up
Down
Down
Up
Up
Up
Up
Up
Down
Up

Effect of changes in

target gene expression Target gene

on Wnt pathway
Inactivate
Inactivate

Activate

Inactivate

Inactivate
Inactivate
Inactivate
Inactivate
Inactivate

Activate

interacts with Reference

Wat

Wat

Wat

Wat

Wat

Wat
HSPG?
Dsh
f-catenin
f-catenin
TCF

f-catenin

Inactivate (Drosophila) f-catenin/

Activate (Zebrafish)

LEF/TCF

(Muller et al. 1999)
(Cadigan et al. 1998)
(Sato et al. 1999)
(Willert et al. 2002)
(Wehrii et al. 2000)
(Baeg et al. 2001)
(Giraldez et al. 2002)
(Rousset et al. 2001)
(Tho et al. 2002)
(Spiegelman et al. 2000)
(Roose et al. 1999)
(CHovanes et al. 2001)

(Zeng & Verheyen 2004,
Thorpe & Moon 2004)

                       Text
0               Target gene
1
2                        Fz
3
4                      Dfz2
..                      ...
97   (CHovanes et al. 2001)
98
99   (Zeng & Verheyen 2004,
100     Thorpe & Moon 2004)
101

[102 rows x 1 columns]

In [29]:
image_file_name = '2_clean_top.png'
img = Image.open(image_path+image_file_name)

#treats image as a single uniform block of text, ignoring any perceived line breaks
custom_config = r'--psm 6'

# Perform OCR with custom configurations
text = pytesseract.image_to_string(img, config=custom_config)

# Print the extracted text
print(text)

# Split the text into lines
lines = text.split('\n')

Effect of Wnt Effect of changes in
signal on target target gene expression Target gene
Target gene gene expression on Wnt pathway interacts with Reference

In [31]:
image_file_name = '2_clean_top.png'
img = Image.open(image_path+image_file_name)

#treats image as a single uniform block of text, ignoring any perceived line breaks
custom_config = r'--psm 11'

# Perform OCR with custom configurations
text = pytesseract.image_to_string(img, config=custom_config)

# Print the extracted text
print(text)

# Split the text into lines
lines = text.split('\n')

Effect of Wnt

Effect of changes in

signal on target target gene expression Target gene

Target gene

gene expression on Wnt pathway

interacts with Reference

In [40]:
image_file_name = '2_clean_singlecell.png'
img = Image.open(image_path+image_file_name)

#treats image as a single uniform block of text, ignoring any perceived line breaks
custom_config = r'--psm 8'

# Perform OCR with custom configurations
text = pytesseract.image_to_string(img, config=custom_config)

# Print the extracted text
print(text)

# Split the text into lines
lines = text.split('\n')

Bs,

In [ ]:
#treats image as a single uniform block of text, ignoring any perceived line breaks
custom_config = r'--psm 6'

# Perform OCR with custom configurations
text = pytesseract.image_to_string(img, config=custom_config)

# Print the extracted text
print(text)

# Split the text into lines
lines = text.split('\n')

In [5]:
import ocr_main

ocr = ocr_main.OCRMain.extract_image(image_file_name='2_clean_top.png', psm=6)
ocr

Effect of Wnt Effect of changes in
signal on target target gene expression Target gene
Target gene gene expression on Wnt pathway interacts with Reference

                                                Text
0                 Effect of Wnt Effect of changes in
1  signal on target target gene expression Target...
2  Target gene gene expression on Wnt pathway int...
3

In [10]:
import ocr_main
coordinates = (0,0,100,100)
ocr = ocr_main.OCRMain.extract_coordinate(image_file_name='2_clean_top.png',coordinates=coordinates, psm=6)

Tarcaat aat